upstream backend {
    server api:3000;
}

upstream frontend {
    server front:80;
}

server {
    listen 80;

    location / {
        proxy_pass http://front;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http:/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
